---
- name: Play - Setup Jenkins Server
  hosts: all
  vars_files:
    - ./vars/vars.yml
    - ./vars/secrets.yml
  become: true

  pre_tasks:
    - debug: var=ansible_os_family
    - name: Load OS specific Vars file
      include_vars: "{{ item }}"
      with_first_found:
        - "./vars/os_specific_{{ ansible_os_family }}.yml"
        - "./vars/os_specific_default.yml"    

  roles:
    - role: geerlingguy.ntp
    - role: geerlingguy.java
    - role: geerlingguy.docker
    - role: geerlingguy.git
    - role: geerlingguy.ansible
    - role: geerlingguy.jenkins

  tasks:
    - name: Install Jenkins-Host-System packages
      package:
        name:
          - git
        state: present
      become: true

