---
- name: Play - Setup Jenkins Server
  hosts: all
  vars_files:
    - ./vars/vars.yml
    - ./vars/secrets.yml
  become: true

  pre_tasks:
    - debug: var=ansible_os_family
    - name: Load OS specific Vars file
      include_vars: "{{ item }}"
      with_first_found:
        - "./vars/os_specific_{{ ansible_os_family }}.yml"
        - "./vars/os_specific_default.yml"    

  roles:
    - role: geerlingguy.ntp
    - role: geerlingguy.java
    - role: geerlingguy.docker
    - role: geerlingguy.git
    - role: geerlingguy.ansible
    - role: geerlingguy.jenkins

  tasks:
    - name: Install Jenkins-Host-System packages
      package:
        name:
          - git
        state: present
      become: true

    - name: Modify user 'Jenkins' to add group 'docker'
      ansible.builtin.user:
        name: jenkins
        groups: docker
        append: yes
    - name: Stop service Jenkins if started
      ansible.builtin.service:
        name: jenkins
        state: stopped        
    # - name: Copy content of directory 'plugins'
    #   copy:
    #     remote_src: true      
    #     src: /var/lib/jenkins/plugins
    #     dest: /mnt/shared_folder/plugins
    - name: Delete Jenkins directory
      ansible.builtin.file:
        state: absent
        path: /var/lib/jenkins
    - name: Recreate Jenkins directory
      ansible.builtin.file:
        state: directory
        path: /var/lib/jenkins
    - name: Extract old Jenkins backup into /var/lib/jenkins
      ansible.builtin.unarchive:
        remote_src: true
        src: /mnt/shared_folder/jenkins-home-folder-2024-05-01.tar.gz
        dest: /var/lib/jenkins/
    # - name: Delete new plugins directory
    #   ansible.builtin.file:
    #     state: absent
    #     path: /var/lib/jenkins/plugins
    # - name: Recreate plugins directory
    #   ansible.builtin.file:
    #     state: directory
    #     path: /var/lib/jenkins/plugins
    # - name: Copy content of directory 'plugins'
    #   copy:
    #     remote_src: true      
    #     src: /mnt/shared_folder/plugins
    #     dest: /var/lib/jenkins/plugins
    - name: Change ownership of the /var/lib/jenkins back to jenkins:jenkins
      file:
        state : directory
        recurse : yes
        path : /var/lib/jenkins
        owner: jenkins
        group: jenkins
